version: "3.3"

services:
    db:
        image: postgres
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
    api-service:
        build: 
            context: ./api-service
        command: "python3 -u main.py"
        ports:
            - "5000:5000"
        volumes:
            - ./api-service:/code
        depends_on:
            - db
    frontend-service:
        build:
            context: ./frontend-service
        command: "npm start"
        ports:
            - "3000:3000"
        stdin_open: true
        volumes:
            - ./frontend-service:/app
        depends_on:
            - api-service
