version: "3.3"

services:
    api-service:
        build: 
            context: ./api-service
        command: "python3 -u main.py"
        ports:
            - "5000:5000"
    frontend-service:
        build:
            context: ./frontend-service
        command: "npm start"
        ports:
            - "3000:3000"
        stdin_open: true
        volumes:
            - ./frontend-service:/app
